baseURL = 'https://cn-4amsleeper.github.io/'
enableEmoji = true
footnotereturnlinkcontents = "↩"
languageCode = 'zh-CN'
title = "CN's Blog"
theme = "hugo-classic" 
[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4

[permalinks]
post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 1
[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 2
[[menu.feed]]
name = "Frontpage"
url = "/CN's Blog/"

[params]
custom_css = ["css/fonts.css"]
description = "I'm still thinking what to write on my tombstone."
footer = "I'm still thinking what to write on my tombstone."